### ISSUE TITLE
Wybranie technologii dla aplikacji

### ISSUE THREAD

**Issue by tp-ckziu2** [tp-ckziu2/todo-list#1]
Czy powinniśmy użyć prostej strony HTML czy dodać jakieś skrypty JavaScript?

**Comment by Filipsys** [comment]
Też tak sądzę

<h1>BEEPbeepbeEP</h1>

**Comment by krzysirk** [comment]
zbieraj bawelne filip

**Comment by krzysirk** [comment]
_**dobry den**_

**Comment by krzysirk** [comment]
<h1>siuuuuuu</h1>
